### ISSUE TITLE
Does not replace the umlauts on windows

### ISSUE THREAD

**Issue by Franklin89** [webchef/jekyll-umlauts#1]
Hi

I just tried this plugin on my windows machine.
This seems not to be working. Do you have any idea what the problem could be?

If I run the command jekyll build, it first says it cant read the file and then it outputs the "Replace 

Thanks

**Comment by ArneGockeln** [comment]
Hi Franklin,

thanks for your issue report.
I do not have a windows machine to test on. But your description sounds like a file owner or write permission issue! 

Could you please post the jekyll log or output from the console?

Best,
Arne

**Comment by Franklin89** [comment]
Hi Arne,

Sorry my bad, the problem occurred due to some permission issues.
Works great now. 

Thanks
